name: nectar_bot
description: "Chatbot-based Ticket Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.19.0
  uuid: ^4.2.1
  image_picker: ^1.0.4
#  file_picker: ^6.1.1
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  drift_dev: ^2.13.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700